// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1fifmayUxkJdEbGi3RmENOcsX_om8NNA',
    appId: '1:688104797032:web:9b836cff94e7942254dcdd',
    messagingSenderId: '688104797032',
    projectId: 'aeroquest-96907',
    authDomain: 'aeroquest-96907.firebaseapp.com',
    storageBucket: 'aeroquest-96907.firebasestorage.app',
    measurementId: 'G-P8Q2XG346Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3xWnUvhdlKHwO-jhjj0mtpDOIYNWenIg',
    appId: '1:688104797032:android:9934a5319407dc3954dcdd',
    messagingSenderId: '688104797032',
    projectId: 'aeroquest-96907',
    storageBucket: 'aeroquest-96907.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvcsWVZPS7lKbMxwC9XIdjj-ZZgq7qvGY',
    appId: '1:688104797032:ios:08d8ac509e542a9e54dcdd',
    messagingSenderId: '688104797032',
    projectId: 'aeroquest-96907',
    storageBucket: 'aeroquest-96907.firebasestorage.app',
    iosBundleId: 'com.example.aeroquestApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvcsWVZPS7lKbMxwC9XIdjj-ZZgq7qvGY',
    appId: '1:688104797032:ios:08d8ac509e542a9e54dcdd',
    messagingSenderId: '688104797032',
    projectId: 'aeroquest-96907',
    storageBucket: 'aeroquest-96907.firebasestorage.app',
    iosBundleId: 'com.example.aeroquestApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1fifmayUxkJdEbGi3RmENOcsX_om8NNA',
    appId: '1:688104797032:web:02e35958c15da7b954dcdd',
    messagingSenderId: '688104797032',
    projectId: 'aeroquest-96907',
    authDomain: 'aeroquest-96907.firebaseapp.com',
    storageBucket: 'aeroquest-96907.firebasestorage.app',
    measurementId: 'G-G8YX4TNLVK',
  );
}
